bin:
  link: "~/.bin"

picom:
  link: "~/.config/picom"
  dependencies:
    - "picom"

dunst:
  link: "~/.config/dunst"
  dependencies:
    - "dunst"

fonts:
  link: "~/.local/share/fonts"

git:
  link: "~"

i3:
  link:
    - "*": "~/.config/i3"
    - ".*": "~/.config/i3"
  dependencies:
    - "i3lock"
    - "rofi"
    - "imagemagick"
    - "xorg-xbacklight"
    - "xclip"
    - "redshift"
    - "ranger"
    - "feh"
    - "scrot"
    - "upower"
    - "python-dbus"
    - "light"
  postlink:
    - "mkdir -p ~/.tmp"
    - "#timedatectl set-ntp true"

i3status:
  link:
    - "*": "~/.config/i3status"
    - ".*": "~/.config/i3status"
  dependencies:
    - "i3status"

mpv:
  link: "~/.config/mpv"
  postlink:
    - "mkdir -p ~/Pictures/Screenshots"
  dependencies:
    - "mpv"

other:
  link: "~"
  dependencies:
    - "qbittorrent"
    - "tlp"

rofi:
  link: "~/.config/rofi"
  dependencies:
    - "rofi"

polybar:
  link: "~/.config/polybar"
  dependencies:
    - "polybar"

ranger:
  link: "~/.config/ranger"
  dependencies:
    - "ranger"
    - "imagemagick"
    - "w3m"
    - "feh"

redshift:
  link: "~/.config/"
  dependencies:
    - "redshift"

system:
  link: "~"
  dependencies:
  - "rxvt-unicode"

vim:
  link:
    - minisnip: "~/.vim"
    - after: "~/.vim"
    - "*": "~"
    - ".*": "~"
  dependencies:
    - "gvim"
    - "curl"
    - "ctags"
    - "pandoc"
    - "python-pip"
    - "the_silver_searcher"
  postlink:
    - "mkdir -p ~/.vim/undo"
    - "mkdir -p ~/.vim/backup"

zathura:
    link:
    - zathurarc: "~/.config/zathura"
    dependencies:
    - "zathura"
    - "zathura-pdf-mupdf"
    - "texlive-most"
