bin:
  link: "~/.bin"

compton:
  link: "~/.config/compton"
  dependencies:
    - "compton"

dunst:
  link: "~/.config/dunst"
  dependencies:
    - "dunst"

fonts:
  link: "~/.local/share/fonts"

git:
  link: "~"

# sudo apt-get purge xserver-xorg-video-intel

i3:
  link:
    - "*": "~/.config/i3"
    - ".*": "~/.config/i3"
  dependencies:
    - "i3lock"
    - "rofi"
    - "xbacklight"
    - "xclip"
    - "ranger"
    - "feh"
    - "scrot"
  postlink:
    - "mkdir -p ~/.tmp"

rofi:
  link: "~/.config/rofi"
  dependencies:
    - "rofi"

# apt install build-essential git cmake cmake-data pkg-config python3-sphinx libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev

# ./build.sh -3 -a -p -f -A -j

polybar:
  link: "~/.config/polybar"
  dependencies:
    - "polybar"
    - "libasound2-dev"
    - "libiw-dev"

ranger:
  link: "~/.config/ranger"
  dependencies:
    - "ranger"
    - "w3m"
    - "feh"

redshift:
  link: "~/.config/"
  dependencies:
    - "redshift"

system:
  link: "~"
  dependencies:
  - "rxvt-unicode"
  - "xrdb"

# Install `system.devel` component
# sudo eopkg install -c system.devel
vim:
  link:
    - minisnip: "~/.vim"
    - after: "~/.vim"
    - "*": "~"
    - ".*": "~"
  dependencies:
    - "gvim"
    - "curl"
    - "ag"
  postlink:
    - "mkdir -p ~/.vim/undodir"
    - "mkdir -p ~/.vim/backup"
