bin:
  link: "~/.bin"

compton:
  link: "~/.config/compton"
  dependencies:
    - "compton"

dunst:
  link: "~/.config/dunst"
  dependencies:
    - "dunst"

git:
  link: "~"

i3:
  link:
    - "*": "~/.config/i3"
    - ".*": "~/.config/i3"
  dependencies:
    - "i3lock"
    - "rofi"
    - "imagemagick"
    - "xbacklight"
    - "xclip"
    - "redshift"
    - "ranger"
    - "feh"
    - "network-manager"
    - "scrot"
  postlink:
    - "mkdir -p ~/.tmp"

i3status:
  link:
    - "*": "~/.config/i3status"
    - ".*": "~/.config/i3status"
  dependencies:
    - "i3status"

ranger:
  link: "~/.config/ranger"
  dependencies:
    - "ranger"
    - "imagemagick"
    - "w3m"
    - "feh"

system:
  link: "~"
  dependencies:
  - "rxvt-unicode"
  - "xrdb"

# Install `system.devel` component
# sudo eopkg install -c system.devel
vim:
  link:
    - minisnip: "~/.vim"
    - after: "~/.vim"
    - "*": "~"
    - ".*": "~"
  dependencies:
    - "vim"
    - "curl"
    - "ctags"
    - "pandoc"
    - "python-pip"
    - "python3-pip"
    - "ag"
  postlink:
    - "mkdir -p ~/.vim/undodir"
    - "mkdir -p ~/.vim/backup"

zathura:
    link:
    - zathurarc: "~/.config/zathura"
    dependencies:
    - "zathura"
    - "texlive-all"
